# Profiles Config for Clash Verge

current: RYfw5aPWDyzS
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1725518786
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1725518786
- uid: mBr5tPTkiZ5Y
  type: merge
  name: null
  file: mBr5tPTkiZ5Y.yaml
  updated: 1725521862
- uid: saroDBdiUjuD
  type: script
  name: null
  file: saroDBdiUjuD.js
  updated: 1725521862
- uid: rqNnJxfcGjqw
  type: rules
  name: null
  file: rqNnJxfcGjqw.yaml
  updated: 1725521862
- uid: p1ODwS5sS3cm
  type: proxies
  name: null
  file: p1ODwS5sS3cm.yaml
  updated: 1725521862
- uid: gZFFymujRuou
  type: groups
  name: null
  file: gZFFymujRuou.yaml
  updated: 1725521862
- uid: L5Gx52QOl6vi
  type: local
  name: socks
  file: L5Gx52QOl6vi.yaml
  desc: socks
  selected:
  - name: GLOBAL
    now: socks-hk
  - name: ChinaIP
    now: DIRECT
  - name: China
    now: DIRECT
  - name: Proxy
    now: socks-hk
  updated: 1725521862
  option:
    merge: mBr5tPTkiZ5Y
    script: saroDBdiUjuD
    rules: rqNnJxfcGjqw
    proxies: p1ODwS5sS3cm
    groups: gZFFymujRuou
- uid: mzsMBlT9LTbA
  type: merge
  name: null
  file: mzsMBlT9LTbA.yaml
  updated: 1727661586
- uid: sHjy4BG9XO4D
  type: script
  name: null
  file: sHjy4BG9XO4D.js
  updated: 1727661586
- uid: rQZumWi9P41P
  type: rules
  name: null
  file: rQZumWi9P41P.yaml
  updated: 1727661586
- uid: pYF9JJPqU9W1
  type: proxies
  name: null
  file: pYF9JJPqU9W1.yaml
  updated: 1727661586
- uid: gywPSEzNfyyU
  type: groups
  name: null
  file: gywPSEzNfyyU.yaml
  updated: 1727661586
- uid: RYfw5aPWDyzS
  type: remote
  name: AmyTelecom_Clash.yaml
  file: RYfw5aPWDyzS.yaml
  url: https://orxyji.xyz/?L1N1YnNjcmlwdGlvbi9DbGFzaD9zaWQ9NTU5NDcmdG9rZW49Qkk3M05jTXVvSFkmbW09NjYwMzMmNjJiNTY5MDY4ZDY4NDM=
  extra:
    upload: 179416077
    download: 19370527412
    total: 53687091200
    expire: 1743120000
  updated: 1728547203
  option:
    merge: mzsMBlT9LTbA
    script: sHjy4BG9XO4D
    rules: rQZumWi9P41P
    proxies: pYF9JJPqU9W1
    groups: gywPSEzNfyyU
